name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/workflows/actions/install
        with:
          install: nuxt-module-template
          
      - name: Format
        run: bun run format

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/workflows/actions/install

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test

      - name: Typecheck
        run: bun run typecheck
